server:
  port: 3000
file-save-path: D:/images/
# 数据库数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/edu?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
      active: dev
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

#开启SQL日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #阿里云 vod
  #不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI5tCpv1BiMfWhYjMigDFT
      keysecret: JbzTwhPObWZZ6yFlFvP9xTWk2n3Ii0